// <auto-generated />
using System;
using LicitacijaService.Entities.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicitacijaService.Migrations
{
    [DbContext(typeof(LicitacijaContext))]
    [Migration("20230211175018_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LicitacijaService.Entities.Licitacija", b =>
                {
                    b.Property<Guid>("LicitacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojLicitacije")
                        .HasColumnType("int");

                    b.Property<int>("GodinaLicitacije")
                        .HasColumnType("int");

                    b.Property<int>("KorakCeneLicitacije")
                        .HasColumnType("int");

                    b.Property<int>("OgranicenjeLicitacije")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramEntitetProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RokLicitacije")
                        .HasColumnType("datetime2");

                    b.HasKey("LicitacijaId");

                    b.HasIndex("ProgramEntitetProgramId");

                    b.ToTable("Licitacija");

                    b.HasData(
                        new
                        {
                            LicitacijaId = new Guid("98992fb8-8ba8-4586-a7a3-6e2b5472897b"),
                            BrojLicitacije = 42,
                            GodinaLicitacije = 2012,
                            KorakCeneLicitacije = 3,
                            OgranicenjeLicitacije = 12,
                            ProgramEntitetProgramId = new Guid("31511a3e-60de-4d24-80c4-00947314092d"),
                            RokLicitacije = new DateTime(2021, 9, 29, 18, 50, 18, 510, DateTimeKind.Local).AddTicks(8815)
                        },
                        new
                        {
                            LicitacijaId = new Guid("9d70d72c-7f57-4323-9eb7-1444ef348220"),
                            BrojLicitacije = 42,
                            GodinaLicitacije = 2012,
                            KorakCeneLicitacije = 3,
                            OgranicenjeLicitacije = 12,
                            ProgramEntitetProgramId = new Guid("6942fde3-13e0-4832-bfbf-8a9a10572b70"),
                            RokLicitacije = new DateTime(2021, 9, 29, 18, 50, 18, 510, DateTimeKind.Local).AddTicks(8879)
                        },
                        new
                        {
                            LicitacijaId = new Guid("684c392b-7871-4d1c-a93d-9d8661adf9e9"),
                            BrojLicitacije = 42,
                            GodinaLicitacije = 2012,
                            KorakCeneLicitacije = 3,
                            OgranicenjeLicitacije = 12,
                            ProgramEntitetProgramId = new Guid("58b116a2-d458-4f72-abe8-be6135ece89e"),
                            RokLicitacije = new DateTime(2021, 9, 29, 18, 50, 18, 510, DateTimeKind.Local).AddTicks(8883)
                        });
                });

            modelBuilder.Entity("LicitacijaService.Entities.ProgramEntitet", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KrugLicitacije")
                        .HasColumnType("int");

                    b.Property<int>("MaksimalnaPovrsina")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.ToTable("ProgramEntitet");

                    b.HasData(
                        new
                        {
                            ProgramId = new Guid("31511a3e-60de-4d24-80c4-00947314092d"),
                            KrugLicitacije = 1,
                            MaksimalnaPovrsina = 200
                        },
                        new
                        {
                            ProgramId = new Guid("6942fde3-13e0-4832-bfbf-8a9a10572b70"),
                            KrugLicitacije = 1,
                            MaksimalnaPovrsina = 300
                        },
                        new
                        {
                            ProgramId = new Guid("58b116a2-d458-4f72-abe8-be6135ece89e"),
                            KrugLicitacije = 2,
                            MaksimalnaPovrsina = 500
                        });
                });

            modelBuilder.Entity("LicitacijaService.Entities.Licitacija", b =>
                {
                    b.HasOne("LicitacijaService.Entities.ProgramEntitet", "ProgramEntitet")
                        .WithMany("Licitacije")
                        .HasForeignKey("ProgramEntitetProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramEntitet");
                });

            modelBuilder.Entity("LicitacijaService.Entities.ProgramEntitet", b =>
                {
                    b.Navigation("Licitacije");
                });
#pragma warning restore 612, 618
        }
    }
}
