// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nadmetanje_microserviceDLL.Context;

#nullable disable

namespace nadmetanjemicroserviceDAL.Migrations
{
    [DbContext(typeof(NadmetanjeContext))]
    [Migration("20230211115317_vrednostJN")]
    partial class vrednostJN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("nadmetanje_microserviceDLL.Model.Etapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LicitacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("VremePocetka")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("VremeZavrsetka")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Etape");
                });

            modelBuilder.Entity("nadmetanje_microserviceDLL.Model.Nadmetanje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CenaPoHektaru")
                        .HasColumnType("float");

                    b.Property<int>("DuzinaZakupa")
                        .HasColumnType("int");

                    b.Property<Guid?>("EtapaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KrugNadmetanja")
                        .HasColumnType("int");

                    b.Property<string>("RedniBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StatusDrugiKrug")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<double>("VrednostJavnogNadmetanja")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EtapaId");

                    b.ToTable("Nadmetanja");
                });

            modelBuilder.Entity("nadmetanje_microserviceDLL.Model.Nadmetanje", b =>
                {
                    b.HasOne("nadmetanje_microserviceDLL.Model.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId");

                    b.Navigation("Etapa");
                });
#pragma warning restore 612, 618
        }
    }
}
