// <auto-generated />
using System;
using KorisnikSistemaServis.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KorisnikSistemaServis.Migrations
{
    [DbContext(typeof(KorisnikContext))]
    partial class KorisnikContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KorisnikSistemaServis.Entities.Korisnik", b =>
                {
                    b.Property<Guid>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipKorisnika")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            KorisnikId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Ime = "Sanja",
                            KorisnickoIme = "sanja123",
                            Lozinka = "$2a$11$gv/Gl4Fa0.wR4vQk74Ijse7i/oQqGzRsVkgZW7ZdPpAkojgKRpS/2",
                            Prezime = "Tica",
                            TipKorisnika = 0
                        },
                        new
                        {
                            KorisnikId = new Guid("9245fe4a-d402-451c-b9ed-9c1a04247482"),
                            Ime = "Jovana",
                            KorisnickoIme = "jovanaj",
                            Lozinka = "$2a$11$FNI2egC0aDwjCTUdVCb2O.y3RDqBGCD2eYwhioDpLLaFmimMz4XMC",
                            Prezime = "Jovanovic",
                            TipKorisnika = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
